# Generated by Django 5.2.6 on 2025-10-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_chauffeur_vehicule_chauffeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la pompe')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Numéro de série')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('debit_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Débit maximum (m³/h)')),
                ('portee_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Portée maximale (m)')),
                ('hauteur_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hauteur maximale (m)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_service', 'En service'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20, verbose_name='Statut')),
                ('date_acquisition', models.DateField(verbose_name="Date d'acquisition")),
                ('date_derniere_maintenance', models.DateField(blank=True, null=True, verbose_name='Dernière maintenance')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pompes_operees', to='logistics.chauffeur', verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Pompe',
                'verbose_name_plural': 'Pompes',
                'ordering': ['nom'],
            },
        ),
    ]
