# Generated by Django 5.2.6 on 2026-10-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_pompe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompe',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Immatriculation'),
        ),
    ]
