# Generated by Django 5.2.6 on 2025-12-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_force_create_table'),
    ]

    operations = [
    ]
