# Generated by Django 5.2.6 on 2025-12-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fournisseurmatierepremiere_prixfournisseurmatiere_and_more'),
        ('stock', '0003_auto_20251212_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisieEntreeLie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=50, verbose_name='Numéro de facture')),
                ('date_facture', models.DateField(blank=True, null=True, verbose_name='Date de facture')),
                ('prix_achat_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat HT")),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fournisseurmatierepremiere', verbose_name='Fournisseur')),
                ('mouvement_stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.mouvementstock', verbose_name='Mouvement de stock')),
            ],
            options={
                'verbose_name': "Saisie d'entrée liée",
                'verbose_name_plural': "Saisies d'entrées liées",
                'ordering': ['-date_creation'],
            },
        ),
    ]
