# Generated by Django 5.2.6 on 2025-12-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fournisseurmatierepremiere_prixfournisseurmatiere_and_more'),
        ('stock', '0004_saisieentreelie'),
    ]

    operations = [
        migrations.AddField(
            model_name='saisieentreelie',
            name='matiere_premiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.matierepremiere', verbose_name='Matière première'),
        ),
        migrations.AddField(
            model_name='saisieentreelie',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='saisieentreelie',
            name='mouvement_stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.mouvementstock', verbose_name='Mouvement de stock'),
        ),
    ]
