# Generated by Django 5.2.6 on 2025-12-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_saisieentreelie_matiere_premiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saisieentreelie',
            name='prix_achat_ht',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Prix d'achat HT"),
        ),
        migrations.AlterField(
            model_name='saisieentreelie',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantité'),
        ),
    ]
