# Generated by Django 5.2.6 on 2025-12-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_saisieentreelie_prix_achat_ht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saisieentreelie',
            name='fournisseur',
            field=models.CharField(max_length=100, verbose_name='Fournisseur'),
        ),
    ]
