# Generated by Django 5.2.6 on 2025-12-30 12:45

import django.db.models.deletion
from django.db import migrations, models


def create_fournisseurs_from_existing_data(apps, schema_editor):
    """Crée des fournisseurs à partir des données existantes dans SaisieEntreeLie"""
    SaisieEntreeLie = apps.get_model('stock', 'SaisieEntreeLie')
    Fournisseur = apps.get_model('stock', 'Fournisseur')
    
    # Récupérer tous les noms de fournisseurs uniques
    fournisseurs_uniques = set()
    for saisie in SaisieEntreeLie.objects.all():
        if saisie.fournisseur:  # Ancien champ CharField
            fournisseurs_uniques.add(saisie.fournisseur)
    
    # Créer les fournisseurs
    fournisseur_mapping = {}
    for nom_fournisseur in fournisseurs_uniques:
        fournisseur, created = Fournisseur.objects.get_or_create(
            nom=nom_fournisseur,
            defaults={
                'actif': True
            }
        )
        fournisseur_mapping[nom_fournisseur] = fournisseur
    
    return fournisseur_mapping


def migrate_fournisseur_data(apps, schema_editor):
    """Migre les données du champ CharField vers ForeignKey"""
    SaisieEntreeLie = apps.get_model('stock', 'SaisieEntreeLie')
    fournisseur_mapping = create_fournisseurs_from_existing_data(apps, schema_editor)
    
    # Mettre à jour toutes les entrées avec les nouveaux fournisseurs
    for saisie in SaisieEntreeLie.objects.all():
        if saisie.fournisseur:  # Ancien champ CharField
            nom_fournisseur = saisie.fournisseur
            if nom_fournisseur in fournisseur_mapping:
                saisie.fournisseur_new = fournisseur_mapping[nom_fournisseur]
                saisie.save()


def reverse_migration(apps, schema_editor):
    """Fonction de rollback"""
    SaisieEntreeLie = apps.get_model('stock', 'SaisieEntreeLie')
    
    for saisie in SaisieEntreeLie.objects.all():
        if saisie.fournisseur_new:
            saisie.fournisseur = saisie.fournisseur_new.nom
            saisie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_saisieentreelie_fournisseur'),
    ]

    operations = [
        # Étape 1 : Créer le modèle Fournisseur
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du fournisseur')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        
        # Étape 2 : Ajouter un champ temporaire pour la migration
        migrations.AddField(
            model_name='saisieentreelie',
            name='fournisseur_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.fournisseur', verbose_name='Fournisseur'),
        ),
        
        # Étape 3 : Migrer les données
        migrations.RunPython(migrate_fournisseur_data, reverse_migration),
        
        # Étape 4 : Supprimer l'ancien champ
        migrations.RemoveField(
            model_name='saisieentreelie',
            name='fournisseur',
        ),
        
        # Étape 5 : Renommer le nouveau champ
        migrations.RenameField(
            model_name='saisieentreelie',
            old_name='fournisseur_new',
            new_name='fournisseur',
        ),
        
        # Étape 6 : Rendre le champ obligatoire
        migrations.AlterField(
            model_name='saisieentreelie',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.fournisseur', verbose_name='Fournisseur'),
        ),
    ]