# Generated by Django 5.2.6 on 2025-09-20 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_facturation'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'ordering': ['ordre', 'id'], 'verbose_name': 'Ligne de facture', 'verbose_name_plural': 'Lignes de facture'},
        ),
        migrations.AddField(
            model_name='facture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_reglement',
            field=models.DateField(blank=True, help_text='Date prévue de règlement', null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='delai_reglement',
            field=models.IntegerField(default=30, help_text='Délai de règlement en jours'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mode_reglement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire'), ('traite', 'Traite')], default='virement', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant hors taxes', max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la TVA', max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_reglement',
            field=models.CharField(blank=True, help_text='Numéro de chèque, virement, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='facture',
            name='objet',
            field=models.CharField(default='Fourniture de béton', help_text='Objet de la facture', max_length=255),
        ),
        migrations.AddField(
            model_name='facture',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence de la facture', max_length=50),
        ),
        migrations.AddField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Taux de TVA en %', max_digits=5),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='ordre',
            field=models.PositiveIntegerField(default=1, help_text="Ordre d'affichage dans la facture"),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='unite',
            field=models.CharField(choices=[('m3', 'Mètre cube (m³)'), ('tonne', 'Tonne'), ('unite', 'Unité'), ('forfait', 'Forfait')], default='m3', help_text='Unité de mesure', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Montant TTC', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='description',
            field=models.CharField(help_text='Description de la prestation', max_length=255),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='montant_ligne',
            field=models.DecimalField(decimal_places=2, help_text='Montant de la ligne HT', max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix unitaire HT', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='quantite',
            field=models.DecimalField(decimal_places=3, help_text='Quantité', max_digits=10),
        ),
    ]
