# Generated by Django 5.2.6 on 2025-09-20 13:09

from django.db import migrations
from datetime import datetime


def populate_reference(apps, schema_editor):
    """Génère des références uniques pour les factures existantes sans référence"""
    Facture = apps.get_model('billing', 'Facture')
    
    for facture in Facture.objects.filter(reference__isnull=True) | Facture.objects.filter(reference=''):
        # Génère une référence basée sur l'ID et la date
        date_str = facture.date_facturation.strftime('%Y%m')
        facture.reference = f"FAC-{date_str}-{facture.id:04d}"
        facture.save()


def reverse_populate_reference(apps, schema_editor):
    """Fonction de retour en arrière (optionnelle)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_facture_options_alter_lignefacture_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_reference, reverse_populate_reference),
    ]
