# Generated by Django 5.2.6 on 2025-09-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_populate_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence de la facture', max_length=50, unique=True),
        ),
    ]
