# Configuration Render pour beton-project - Force Deploy ChantierViewSet Fix: 2024-01-20-15h30
services:
  - type: web
    name: beton-project
    env: python
    plan: free
    buildCommand: "python render_build.py"
    startCommand: "python manage.py migrate --noinput && python create_superuser.py && gunicorn beton_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: beton_project.settings
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: beton-project.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
      - key: DATABASE_URL
        fromDatabase:
          name: beton-db
          property: connectionString

databases:
  - name: beton-db
    databaseName: beton_project
    user: beton_user
    plan: free