# Generated by Django 5.2.6 on 2025-09-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormuleBeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('resistance_requise', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionFormule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.matierepremiere')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='formulas.formulebeton')),
            ],
            options={
                'unique_together': {('formule', 'matiere_premiere')},
            },
        ),
    ]
