# Generated by Django 5.2.6 on 2025-09-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulebeton',
            name='quantite_produite_reference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
