# Generated by Django 5.2.6 on 2026-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_formulebeton_quantite_produite_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulebeton',
            name='prix_vente_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de vente unitaire par m³', max_digits=10),
        ),
    ]
