# Generated by Django 5.2.6 on 2025-09-15 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulas', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_production', models.DateField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.commande')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.formulebeton')),
            ],
        ),
        migrations.CreateModel(
            name='LotProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_heure_production', models.DateTimeField(auto_now_add=True)),
                ('ordre_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='production.ordreproduction')),
            ],
        ),
    ]
