# Generated by Django 5.2.6 on 2025-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreproduction',
            name='matieres_sorties_calculees',
            field=models.BooleanField(default=False),
        ),
    ]
