# Generated by Django 5.2.6 on 2025-09-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_add_numero_bon_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordreproduction',
            name='numero_bon',
            field=models.CharField(blank=True, help_text='Numéro de bon de production', max_length=20, null=True, unique=True),
        ),
    ]
