# Generated by Django 5.2.6 on 2025-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_add_unique_constraint_numero_bon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreproduction',
            name='heure_production',
            field=models.TimeField(blank=True, help_text='Heure prévue de production', null=True),
        ),
    ]
