# Generated by Django 5.2.6 on 2025-10-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_chauffeur_vehicule_chauffeur'),
        ('production', '0005_add_heure_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreproduction',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production', to='logistics.chauffeur'),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production', to='logistics.vehicule'),
        ),
    ]
