# Generated by Django 5.2.6 on 2025-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_ordreproduction_chauffeur_ordreproduction_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreproduction',
            name='adjuvant_type',
            field=models.CharField(blank=True, choices=[('Plastifiant', 'Plastifiant'), ('Superplastifiant', 'Superplastifiant'), ('Retardateur', 'Retardateur'), ('Accélérateur', 'Accélérateur'), ("Entraîneur d'air", "Entraîneur d'air")], help_text='Type d’adjuvant', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='ciment_type_classe',
            field=models.CharField(blank=True, choices=[('CEM I 42.5R', 'CEM I 42.5R'), ('CEM II/A-M 42.5N', 'CEM II/A-M 42.5N'), ('CEM II/B-M 32.5N', 'CEM II/B-M 32.5N'), ('CEM III/A 42.5N', 'CEM III/A 42.5N')], help_text='Type et classe de ciment', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='classe_consistance',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5')], help_text='Classe de consistance', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='classe_exposition',
            field=models.CharField(blank=True, choices=[('XC1', 'XC1'), ('XC2', 'XC2'), ('XC3', 'XC3'), ('XC4', 'XC4'), ('XD1', 'XD1'), ('XD2', 'XD2'), ('XD3', 'XD3'), ('XS1', 'XS1'), ('XS2', 'XS2'), ('XS3', 'XS3'), ('XF1', 'XF1'), ('XF2', 'XF2'), ('XF3', 'XF3'), ('XF4', 'XF4'), ('XA1', 'XA1'), ('XA2', 'XA2'), ('XA3', 'XA3'), ('XM1', 'XM1'), ('XM2', 'XM2'), ('XM3', 'XM3')], help_text="Classe d'exposition", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='classe_teneur_chlorure',
            field=models.CharField(blank=True, choices=[('CL 0.10', 'CL 0.10'), ('CL 0.20', 'CL 0.20'), ('CL 0.40', 'CL 0.40')], help_text='Classe de teneur en chlorure', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='d_max',
            field=models.CharField(blank=True, choices=[('8', '8 mm'), ('12', '12 mm'), ('16', '16 mm'), ('20', '20 mm'), ('22.4', '22.4 mm'), ('31.5', '31.5 mm'), ('40', '40 mm')], help_text='Granulométrie D max', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='masse_volumique',
            field=models.CharField(blank=True, choices=[('2200 kg/m³', '2200 kg/m³'), ('2300 kg/m³', '2300 kg/m³'), ('2400 kg/m³', '2400 kg/m³'), ('2500 kg/m³', '2500 kg/m³')], help_text='Masse volumique', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='pompe',
            field=models.CharField(blank=True, choices=[('Aucune', 'Aucune'), ('Pompe mobile', 'Pompe mobile'), ('Pompe stationnaire', 'Pompe stationnaire'), ('Tremie', 'Trémie')], help_text='Pompe', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='rapport_e_c',
            field=models.CharField(blank=True, choices=[('0.35', '0.35'), ('0.40', '0.40'), ('0.45', '0.45'), ('0.50', '0.50'), ('0.55', '0.55'), ('0.60', '0.60')], help_text='Rapport E/C', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='temperature_beton',
            field=models.CharField(blank=True, choices=[('10°C', '10°C'), ('15°C', '15°C'), ('20°C', '20°C'), ('25°C', '25°C'), ('30°C', '30°C'), ('35°C', '35°C')], help_text='Température du béton', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='teneur_en_air',
            field=models.CharField(blank=True, choices=[('1%', '1%'), ('2%', '2%'), ('3%', '3%'), ('4%', '4%'), ('5%', '5%')], help_text='Teneur en air', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='teneur_en_ciment',
            field=models.CharField(blank=True, choices=[('300 kg/m³', '300 kg/m³'), ('320 kg/m³', '320 kg/m³'), ('350 kg/m³', '350 kg/m³'), ('380 kg/m³', '380 kg/m³'), ('400 kg/m³', '400 kg/m³')], help_text='Teneur en ciment', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='transporteur',
            field=models.CharField(blank=True, choices=[('Interne', 'Interne'), ('Sous-traitant', 'Sous-traitant'), ('Client', 'Client')], help_text='Transporteur', max_length=20, null=True),
        ),
    ]
