# Generated by Django 5.2.6 on 2025-10-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_pompe'),
        ('production', '0007_ordreproduction_adjuvant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordreproduction',
            name='pompe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production', to='logistics.pompe', verbose_name='Pompe'),
        ),
    ]
