# Generated by Django 5.2.6 on 2025-10-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_pompe'),
        ('production', '0007_ordreproduction_adjuvant_type_and_more'),
    ]

    operations = [
        # Nettoyage des valeurs non numériques avant la conversion en ForeignKey (bigint)
        migrations.RunSQL(
            sql=(
                """
                UPDATE production_ordreproduction
                SET pompe = NULL
                WHERE pompe IS NOT NULL AND (
                    pompe IN ('Aucune','None','', 'Pompe mobile','Pompe stationnaire','Tremie','Trémie')
                    OR NOT pompe ~ '^[0-9]+$'
                );
                """
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='ordreproduction',
            name='pompe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production', to='logistics.pompe', verbose_name='Pompe'),
        ),
    ]
