# Generated by Django 5.2.6 on 2025-10-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_commercialdashboard_agentcommercial'),
        ('logistics', '0003_pompe'),
        ('production', '0015_remove_temp_pompe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreproduction',
            name='agent_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production', to='customers.agentcommercial', verbose_name='Agent commercial'),
        ),
        migrations.AlterField(
            model_name='ordreproduction',
            name='pompe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production', to='logistics.pompe', verbose_name='Pompe'),
        ),
    ]
