# Generated by Django 5.2.6 on 2025-10-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_ordreproduction_agent_commercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordreproduction',
            name='ciment_type_classe',
            field=models.CharField(blank=True, choices=[('CPJ 55', 'CPJ 55'), ('CPJ 55 PM', 'CPJ 55 PM')], help_text='Type et classe de ciment', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordreproduction',
            name='classe_exposition',
            field=models.CharField(blank=True, choices=[('X0', 'X0'), ('XCA1', 'XCA1'), ('XCA2', 'XCA2'), ('XM1', 'XM1'), ('XM2', 'XM2'), ('XCL', 'XCL'), ('XG1', 'XG1'), ('XG2', 'XG2'), ('XA1', 'XA1'), ('XA2', 'XA2'), ('XA3', 'XA3')], help_text="Classe d'exposition", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordreproduction',
            name='rapport_e_c',
            field=models.CharField(blank=True, choices=[('0.35', '0.35'), ('0.40', '0.40'), ('0.45', '0.45'), ('0.50', '0.50'), ('0.55', '0.55'), ('0.60', '0.60'), ('0.65', '0.65')], help_text='Rapport E/C', max_length=10, null=True),
        ),
    ]
