# Generated by Django 5.2.6 on 2026-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_alter_ordreproduction_ciment_type_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreproduction',
            name='prix_vente_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente unitaire par m³ pour cet ordre', max_digits=10, null=True),
        ),
    ]
