# Generated by Django 5.2.6 on 2026-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_ordreproduction_prix_vente_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreproduction',
            name='prix_deplacement_camion',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de déplacement du camion', max_digits=10),
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='prix_deplacement_pompe',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de déplacement de la pompe', max_digits=10),
        ),
    ]
