# Generated by Django 5.2.6 on 2025-09-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='seuil_bas',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Seuil en dessous duquel le stock est considéré comme bas', max_digits=10),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='seuil_critique',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Seuil en dessous duquel le stock est considéré comme critique', max_digits=10),
        ),
    ]
