# Generated by Django 5.2.6 on 2025-12-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_matierepremiere_seuil_bas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FournisseurMatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur Matière Première',
                'verbose_name_plural': 'Fournisseurs Matières Premières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PrixFournisseurMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fournisseurmatierepremiere')),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.matierepremiere')),
            ],
            options={
                'verbose_name': 'Prix Fournisseur Matière',
                'verbose_name_plural': 'Prix Fournisseurs Matières',
                'ordering': ['fournisseur', 'matiere_premiere', '-date_debut'],
                'unique_together': {('fournisseur', 'matiere_premiere', 'date_debut')},
            },
        ),
        migrations.AddField(
            model_name='fournisseurmatierepremiere',
            name='matieres_premieres',
            field=models.ManyToManyField(through='inventory.PrixFournisseurMatiere', to='inventory.matierepremiere'),
        ),
    ]
