# Generated by Django 5.2.6 on 2025-09-19 10:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSeuilsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_critique', models.DecimalField(decimal_places=2, default=Decimal('10.0'), help_text='Seuil en dessous duquel le stock est considéré comme critique', max_digits=10)),
                ('seuil_bas', models.DecimalField(decimal_places=2, default=Decimal('50.0'), help_text='Seuil en dessous duquel le stock est considéré comme bas', max_digits=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.CharField(blank=True, help_text='Utilisateur qui a modifié la configuration', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Configuration des seuils de stock',
                'verbose_name_plural': 'Configuration des seuils de stock',
            },
        ),
    ]
