# Generated by Django 5.2.6 on 2025-12-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_formulebeton_quantite_produite_reference'),
        ('inventory', '0003_fournisseurmatierepremiere_prixfournisseurmatiere_and_more'),
        ('reports', '0002_configurationseuilsstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportCoutFormule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('cout_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Coût total')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.formulebeton', verbose_name='Formule béton')),
            ],
            options={
                'verbose_name': 'Rapport de coût de formule',
                'verbose_name_plural': 'Rapports de coût de formule',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DetailCoutFormule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire_moyen', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire moyen')),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût total')),
                ('nombre_saisies', models.IntegerField(default=0, verbose_name='Nombre de saisies utilisées')),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.matierepremiere', verbose_name='Matière première')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='reports.rapportcoutformule')),
            ],
            options={
                'verbose_name': 'Détail coût matière première',
                'verbose_name_plural': 'Détails coût matière première',
                'unique_together': {('rapport', 'matiere_premiere')},
            },
        ),
    ]
