# Generated by Django 5.2.6 on 2025-09-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chantier',
            options={'verbose_name': 'Chantier', 'verbose_name_plural': 'Chantiers'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
