# Generated by Django 5.2.6 on 2025-10-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Tableau de bord commercial',
                'verbose_name_plural': 'Tableau de bord commercial',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.client',),
        ),
        migrations.CreateModel(
            name='AgentCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='agents', to='customers.client')),
            ],
            options={
                'verbose_name': 'Agent commercial',
                'verbose_name_plural': 'Agents commerciaux',
            },
        ),
    ]
