# Generated by Django 5.2.6 on 2025-10-21 10:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulas', '0002_formulebeton_quantite_produite_reference'),
        ('inventory', '0002_matierepremiere_seuil_bas_and_more'),
        ('orders', '0003_commande_heure_livraison_souhaitee'),
        ('production', '0017_alter_ordreproduction_ciment_type_classe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCoût',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_categorie', models.CharField(choices=[('matiere_premiere', 'Matière première'), ('main_oeuvre', "Main d'œuvre"), ('frais_generaux', 'Frais généraux'), ('transport', 'Transport'), ('energie', 'Énergie'), ('amortissement', 'Amortissement'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de coût',
                'verbose_name_plural': 'Catégories de coûts',
                'ordering': ['type_categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CoûtMainOeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_activite', models.CharField(choices=[('production', 'Production'), ('transport', 'Transport'), ('livraison', 'Livraison'), ('maintenance', 'Maintenance'), ('administration', 'Administration'), ('commercial', 'Commercial')], max_length=20)),
                ('coût_horaire_base', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('charges_sociales_pourcentage', models.DecimalField(decimal_places=2, default=45.0, help_text='Pourcentage de charges sociales', max_digits=5)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Coût main d'œuvre",
                'verbose_name_plural': "Coûts main d'œuvre",
                'ordering': ['type_activite', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CalculCoûtRevient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_calculee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite_mesure', models.CharField(default='m³', max_length=10)),
                ('coût_matieres_premieres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coût_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coût_frais_generaux', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coût_transport', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coût_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coût_unitaire_matieres', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('coût_unitaire_main_oeuvre', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('coût_unitaire_frais_generaux', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('coût_unitaire_transport', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('coût_unitaire_total', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('calculé_par', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.commande')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.formulebeton')),
                ('ordre_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.ordreproduction')),
            ],
            options={
                'verbose_name': 'Calcul coût de revient',
                'verbose_name_plural': 'Calculs coûts de revient',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='CoûtFraisGeneraux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type_repartition', models.CharField(choices=[('fixe', 'Montant fixe'), ('pourcentage_ca', 'Pourcentage du CA'), ('par_m3', 'Par m³ produit'), ('par_commande', 'Par commande')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_calculation.categoriecoût')),
            ],
            options={
                'verbose_name': 'Frais généraux',
                'verbose_name_plural': 'Frais généraux',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CoûtMatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, help_text='Prix par unité de mesure', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100)),
                ('coût_transport', models.DecimalField(decimal_places=2, default=0, help_text='Coût de transport par unité', max_digits=10)),
                ('coût_stockage', models.DecimalField(decimal_places=2, default=0, help_text='Coût de stockage par unité', max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coûts', to='inventory.matierepremiere')),
            ],
            options={
                'verbose_name': 'Coût matière première',
                'verbose_name_plural': 'Coûts matières premières',
                'ordering': ['-date_debut', 'matiere_premiere__nom'],
            },
        ),
        migrations.CreateModel(
            name='DetailCoûtMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=4, max_digits=10)),
                ('coût_total_matiere', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calcul_coût', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_matieres', to='cost_calculation.calculcoûtrevient')),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.matierepremiere')),
            ],
            options={
                'verbose_name': 'Détail coût matière',
                'verbose_name_plural': 'Détails coûts matières',
            },
        ),
    ]
