# Generated by Django 5.2.6 on 2025-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_commande_chantier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='heure_livraison_souhaitee',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
