# Generated by Django 5.2.6 on 2025-10-07 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('NEW_ORDER', 'Nouvelle commande'), ('PRODUCTION_UPDATE', 'Mise à jour production'), ('LOW_INVENTORY', 'Stock faible'), ('DELIVERY', 'Livraison'), ('GENERAL', 'Général')], default='GENERAL', max_length=20, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priorité')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet lié')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type objet lié')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
