# Generated by Django 5.2.6 on 2025-09-21 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('quantite_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seuil_minimum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('message', models.TextField()),
                ('vue', models.BooleanField(default=False, help_text='Alerte vue par un utilisateur')),
            ],
            options={
                'verbose_name': 'Alerte de stock',
                'verbose_name_plural': 'Alertes de stock',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom/Identifiant de l'engin", max_length=100)),
                ('numero_serie', models.CharField(blank=True, help_text='Numéro de série', max_length=50)),
                ('immatriculation', models.CharField(blank=True, help_text="Plaque d'immatriculation", max_length=20)),
                ('marque', models.CharField(blank=True, help_text="Marque de l'engin", max_length=50)),
                ('modele', models.CharField(blank=True, help_text="Modèle de l'engin", max_length=50)),
                ('annee', models.PositiveIntegerField(blank=True, help_text='Année de fabrication', null=True)),
                ('actif', models.BooleanField(default=True, help_text='Engin en service')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Engin',
                'verbose_name_plural': 'Engins',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du fournisseur', max_length=100)),
                ('contact', models.CharField(blank=True, help_text='Personne de contact', max_length=100)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Adresse email', max_length=254)),
                ('adresse', models.TextField(blank=True, help_text='Adresse du fournisseur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantité actuelle en stock (litres)', max_digits=10)),
                ('seuil_minimum', models.DecimalField(decimal_places=2, default=Decimal('500'), help_text="Seuil d'alerte minimum (litres)", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock de gasoil',
                'verbose_name_plural': 'Stock de gasoil',
            },
        ),
        migrations.CreateModel(
            name='TypeEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Type d'engin", max_length=50, unique=True)),
                ('consommation_moyenne', models.DecimalField(decimal_places=2, help_text='Consommation moyenne en litres/heure', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': "Type d'engin",
                'verbose_name_plural': "Types d'engins",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date de consommation')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité consommée en litres', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('responsable', models.CharField(help_text="Responsable de l'opération", max_length=100)),
                ('heures_fonctionnement', models.DecimalField(blank=True, decimal_places=2, help_text='Heures de fonctionnement (optionnel)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('kilometrage', models.PositiveIntegerField(blank=True, help_text='Kilométrage (pour véhicules)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes ou observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('engin', models.ForeignKey(help_text='Engin concerné', on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='fuel_management.engin')),
            ],
            options={
                'verbose_name': 'Consommation',
                'verbose_name_plural': 'Consommations',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date de livraison')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité en litres', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prix_unitaire', models.DecimalField(decimal_places=3, help_text='Prix par litre en DH', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Montant total en DH', max_digits=12)),
                ('numero_bon', models.CharField(blank=True, help_text='Numéro de bon de livraison', max_length=50)),
                ('numero_facture', models.CharField(blank=True, help_text='Numéro de facture', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes ou observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(help_text='Fournisseur', on_delete=django.db.models.deletion.CASCADE, to='fuel_management.fournisseur')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='engin',
            name='type_engin',
            field=models.ForeignKey(help_text="Type d'engin", on_delete=django.db.models.deletion.CASCADE, to='fuel_management.typeengin'),
        ),
    ]
