# Generated by Django 5.2.6 on 2026-10-01 18:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total en DH', max_digits=12),
        ),
        migrations.AddField(
            model_name='consommation',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text="Prix par litre en DH (par défaut: dernier prix d'approvisionnement)", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
