# Generated by Django 5.2.6 on 2026-10-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_management', '0002_consommation_montant_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='numero_bon',
            field=models.CharField(blank=True, help_text='Numéro de bon / bordereau de sortie', max_length=50),
        ),
    ]
